# Generated by Django 4.0 on 2022-01-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('transcription1', models.TextField()),
                ('transcription2', models.TextField()),
                ('transcription3', models.TextField()),
                ('transcription4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NarrowIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('transcription1', models.TextField()),
                ('transcription2', models.TextField()),
                ('transcription3', models.TextField()),
                ('transcription4', models.TextField()),
            ],
        ),
    ]
